version: '2.2'
services:
  v2ray:
    image: "v2fly/v2fly-core:v4.38.3"
    restart: always
    hostname: "v2ray"
    volumes:
    - ./v2ray.json:/etc/v2ray/config.json
    - /etc/localtime:/etc/localtime:ro

  caddy:
    image: "caddy:2.1.1-alpine"
    restart: always
    hostname: "caddy"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile 
    - ./html:/html
    ports:
      - "80:80"
      - "443:443"
      - "21312:8080"

